### ISSUE TITLE
[gh-pages] last example doesn't work

### ISSUE THREAD

**Issue by marcelklehr** [mohayonao/timbre#1]
Have a look at [Object.defineProperty](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Object/defineProperty). You have to pass an object, not a function...

Everything else: Great work!

**Comment by mohayonao** [comment]
I checked your issue, every demo work correctly.
Push the [play] button in first to work a demo.

But I failed to write wrong HTML, fix it later. Thank you.

**Comment by marcelklehr** [comment]
Yeah, demo works -- text doesn't... ;)
