### ISSUE TITLE
Safari 6 beta

### ISSUE THREAD

**Issue by spjnowak** [mohayonao/timbre#2]
Hi

I don't know if you have access to the developer beta of Safari 6, which supports the web audio API, but none of your demos work with it. All of the standard (Chromium) web audio examples work fine. 

Stefan

**Comment by mohayonao** [comment]
Fixing up this issue, Timbre.js works with the developer beta of Safari 6.
Thanks!

Nao

**Comment by spjnowak** [comment]
Excellent! Thanks for the swift response. Next question - will it work in mobile Safari on iOS6? I haven't tried yet but I've read that web audio is broken on the current device beta but may be OK on the simulator.

**Comment by spjnowak** [comment]
Just found a problem in your Audio example in documentation (http://mohayonao.github.com/timbre/documents/audio.html) which fails at line 4457 ...
                    _.buffer = ctx.createBuffer(xhr.response, true).getChannelData(0);

**Comment by mohayonao** [comment]
Safari doesn't support Ogg Vorbis, and Chrome doesn't support MP3.

I improved T("audio") object that swap the file extension for different browsers.
i.e. T("audio", src="public/audio/sample.ogg,mp3")

**Comment by mohayonao** [comment]
I updated timbre.js for iOS6, it works with the mobile safari on iOS6.
